### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by Fab16BSB** [DUT-Info-Montreuil/SecretarIA#17]
Traceback (most recent call last):
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\Lancement.py", line 592, in <module>
    main(args)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\Lancement.py", line 534, in main
    train_df, val_df, vocab, max_size, responses = prepare_data(problem_type, preprocessing, regenerate_response_json,
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\Lancement.py", line 280, in prepare_data
    return faire_preparation_donnees(problem_type, regenerate_response, file_name_dataset)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\Lancement.py", line 174, in faire_preparation_donnees
    df, vocab, max_size, responses = preprocessing_df(df=None, file_name=file_name_dataset,
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 604, in preprocessing_df
    max_size = get_max_size(df, problem_type)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 375, in get_max_size
    resultat["X"] = int(max(len(mot) for mot in df[X_COLUMN_VECTORIZED_NAME].tolist()))
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 375, in <genexpr>
    resultat["X"] = int(max(len(mot) for mot in df[X_COLUMN_VECTORIZED_NAME].tolist()))
TypeError: object of type 'generator' has no len()

**Comment by llichten29** [comment]
Je ne l'ai jamais rencontré avec quelle paramètre le bug survient ?

**Comment by Fab16BSB** [comment]
@llichten29 Ah oui j'ai oublier de fermé l'issue j'ai corrigé le bug il manquant les [ ] aux listes de comprehension lors de préparation des données dans les apply
