### ISSUE TITLE
Erreur dossier not found

### ISSUE THREAD

**Issue by Fab16BSB** [DUT-Info-Montreuil/SecretarIA#8]
Traceback (most recent call last):
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 915, in <module>
    main(args.model_type, args.preprocessing, args.dropout, args.training)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 767, in main
    models_dir_files = [d for d in sorted(PATH_TO_MODELS_DIR.iterdir())
IndexError: list index out of range

Quand j'execute alors que j'ai pas le dossier model : 

Paramètre du main :
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Construction de modèles de réseaux de neurones récurrents")
    parser.add_argument('model_type', type=str, choices=['LSTM', 'GRU', 'MGU'], default='LSTM',
                        help="Le type de modèle à utiliser", nargs='?')
    parser.add_argument('preprocessing', type=lambda x: (bool(x) is True or bool(x) is False),
                        default=False, help="Refaire la préparation des données ou non", nargs='?')
    parser.add_argument('dropout', type=lambda x: (0.0 <= float(x) <= 1.0),
                        default=0.25, help="Le taux de dropout (entre 0 et 1)", nargs='?')

    parser.add_argument('training', type=lambda x: (bool(x) is True or bool(x) is False),
                        default=False, nargs='?', help="Refaire l'entrainement ou non")

Faut mettre True a training ? 
Ya ecrit "Refaire l'entrainement ou non" techniquement je ne l'ai même pas fait j'ai pas de model actuellement c'est faire et refaire ? 
Et c'est une erreur de mauvaise utilisation de ma part ?
Quoi qu'il en soit a corrigé pour qu'il n'y ai plus cette erreur

**Comment by Fab16BSB** [comment]
Si je met a true pareil même probleme : 


Traceback (most recent call last):
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 915, in <module>
    main(args.model_type, args.preprocessing, args.dropout, args.training)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 763, in main
    vocab_dir_files = [f for f in os.listdir(PATH_TO_VOCAB_DIR) if
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\fab_1\\PycharmProjects\\SecretarIA\\models\\vocabulaire'

**Comment by Fab16BSB** [comment]
Attention aux tests sur ton PC ca marche mais pas forcement sur le notre.
Après dans certain cas j'abuse c'est vrai x)
Mais je me dis que plus tard un autre stagiaire reprendra peut être le code après toi et il aura les même difficulté aucune connaisse en IA + faudra qu'il comprenne le code déjà existant donc faut sécurisé au max ce genre de detail.

Si tu veux mon conseil : quand je test j'essaye de cassé le programme par tout les moyens si je n'y arrive pas alors j'en conclus qu'il est sécurisé.
