### ISSUE TITLE
KeyError(key) from err KeyError: 'encoder_input_data'

### ISSUE THREAD

**Issue by Fab16BSB** [DUT-Info-Montreuil/SecretarIA#9]
Quand je lance le code que je mettent True ou False a la preparation des données j'ai le droit a ca :

Traceback (most recent call last):
  File "C:\Users\fab_1\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'encoder_input_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 915, in <module>
    main(args.model_type, args.preprocessing, args.dropout, args.training)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 773, in main
    df, vocab, max_size = preprocessing_df(False,
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 670, in preprocessing_df
    df = read_csv(file_name)
  File "C:\Users\fab_1\PycharmProjects\SecretarIA\src\utils.py", line 129, in read_csv
    df[X_COLUMN_VECTORIZED_NAME] = df[X_COLUMN_VECTORIZED_NAME].apply(lambda x: list(map(int, x.strip('[]').split())))
  File "C:\Users\fab_1\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\fab_1\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'encoder_input_data'

**Comment by Fab16BSB** [comment]
En responsable ce code ajouter dans la fonction de lecture du CSV que j'ai mis en commentaire :

def read_csv(file_name: str, path: Path = PATH_TO_DATA_DIR, extension: str = ".csv") -> pd.DataFrame:
    """
    Lire un fichier CSV dans un DataFrame.

    Args:
        file_name (str): Le nom du fichier CSV.
        path (Path, optional): Le chemin du fichier CSV. Par défaut PATH_TO_DATA_DIR.
        extension (str, optional): L'extension du fichier. Par défaut ".csv".

    Returns:
        pd.DataFrame: Le DataFrame créé à partir du fichier CSV.
    """
    path = str(path / file_name)
    if not file_name.endswith(extension):
        path += extension
    df = pd.read_csv(path)

    '''
    df[X_COLUMN_VECTORIZED_NAME] = df[X_COLUMN_VECTORIZED_NAME].apply(lambda x: list(map(int, x.strip('[]').split())))
    df[Y_COLUMN_VECTORIZED_INPUT_NAME] = df[Y_COLUMN_VECTORIZED_INPUT_NAME].apply(
        lambda x: list(map(int, x.strip('[]').split()))
    )
    df[Y_COLUMN_VECTORIZED_OUTPUT_NAME] = (df[Y_COLUMN_VECTORIZED_OUTPUT_NAME].apply
                                           (lambda x: list(map(int, x.strip('[]').split()))))
    '''
    return df
